### ISSUE TITLE
Separate icon for empty folders similar to eza

### ISSUE THREAD

**Issue by eblis** [chrisant996/dirx#4]
Just noticed a very small difference between `dirx` and `eza` while comparing preview results for `fzf` after I just noticed you added `--tree` view 😄 

EZA has a different icon for empty folders, whereas dirx has the same icon for all folders, empty or non-empty.

Not sure if you want to address this, it's quite a small issue but I thought I'd log it anyway.
Notice the difference for `tags` folder.

Eza tree view:
![image](https://github.com/chrisant996/dirx/assets/540188/2046082f-36d1-40b9-b536-d966772387f0)

DirX tree view:
![image](https://github.com/chrisant996/dirx/assets/540188/b44eac26-7052-451a-a6ea-caccbcc68b05)

**Comment by chrisant996** [comment]
We can leave this open for now.  There's a good chance it will never happen.  I'm opposed to incurring that amount of performance loss for a subtle cosmetic detail, especially since (1) the effort to optimize it to infer emptiness with help from other flags and states would be fairly large and (2) it gets confusing/ambiguous when a wildcard is used (and eza currently just fails when given wildcards).

But that led me to notice that `--tree` is not handling wildcards properly in subdirectories (only with `--tree`).

**Comment by chrisant996** [comment]
v0.13 includes fixes for `--tree` with wildcards, `--levels=1`, among other things.

**Comment by eblis** [comment]
Wow, that was fast .. thanks !
