### ISSUE TITLE
Show git status for folder based on status of files inside the subtree

### ISSUE THREAD

**Issue by saumyajyoti** [chrisant996/dirx#6]
Eza or LSD shows git status for parent folder. Can Dirx show the same when file under that folder is changed?

**Comment by chrisant996** [comment]
> Eza or LSD shows git status for parent folder. Can Dirx show the same when file under that folder is changed?

I'm not sure what you're trying to ask.

Can you show the eza command line you use, and sample output?

**Comment by saumyajyoti** [comment]
Thanks for quick reply. Attaching screenshot for comparison.
The git status for 2 files under subtree are modified. But Dirx does not show unless we go to the folder containing the file.
![image](https://github.com/user-attachments/assets/7ee61352-58ef-44f2-bf78-67f72ba63ff8)

**Comment by chrisant996** [comment]
dirx currently only looks for a `.git` subdirectory.

Is there a `.git` subdirectory under the AppData directory?
Or is there a `.git` _file_ under the AppData directory?
Or is it using a different mechanism?

**Comment by saumyajyoti** [comment]
Hi @chrisant996 , yes .git folder is in current path i.e. C:\Users\smukhe5.gar\.local\share\chezmoi\.git

**Comment by saumyajyoti** [comment]
I think dirx shows file status correctly, it never show any git status for containing folder.

**Comment by chrisant996** [comment]
Oh, thanks for clarifying, now I understand, and I can reproduce the behavior.

It's behaving as intended, but only because it didn't occur to me to synthesize status for folders.

In eza [here](https://github.com/eza-community/eza/blob/665c1cb013f2ee2478a5d5cf132aefc17384925d/src/fs/feature/git.rs#L260-L269) and [here](https://github.com/eza-community/eza/blob/665c1cb013f2ee2478a5d5cf132aefc17384925d/src/fs/feature/git.rs#L349-L376) it has a priority order for which status character to show for a directory that contains multiple files with different actions.

I'll add similar behavior in dirx.

**Comment by chrisant996** [comment]
v0.20 has been published and includes this.

**Comment by saumyajyoti** [comment]
Thanks @chrisant996 . This was real quick. Yes, I see git modified status is matching Eza/LSD behavior now. 
Though the git ignore flag "I" is shown differently for folders in eza/lsd/dirx. Maybe policy is different there in all three in how to handle sub tree and global gitignore for files vs folders. That is not critical for me , so will ignore for now.

**Comment by chrisant996** [comment]
> the git ignore flag "I" is shown differently for folders in eza/lsd/dirx

Differently in what way?

**Comment by saumyajyoti** [comment]
Thanks @chrisant996 . I think that is right. As I see in screenshot below with v 0.20.  Here .wtree folder is added to ignore list. 

![image](https://github.com/user-attachments/assets/dab5258b-3664-4deb-8127-04050f6f21b0)

**Comment by saumyajyoti** [comment]
Will test once v0.21 is released.

**Comment by chrisant996** [comment]
Yup cool, I'll publish it later tonight.

**Comment by chrisant996** [comment]
Published.

**Comment by saumyajyoti** [comment]
Thanks @chrisant996 . It matched most of the part. Serves the common purpose. Except the case where there is a local folder added under global gitignore. e.g. .wtree folder here. which is ignored via git config:
 excludesfile = ~/global.gitignore

![image](https://github.com/user-attachments/assets/3cb19d46-caf1-4472-b9f1-529f40687937)

**Comment by chrisant996** [comment]
> Except the case where there is a local folder added under global gitignore. e.g. .wtree folder here. which is ignored via git config:
>  excludesfile = ~/global.gitignore

Tilde syntax is a thing in git on Windows?

Ok I'll research what other Linux idioms git supports on Windows as well.  🤷🏻‍♂️

**Comment by saumyajyoti** [comment]
Thanks. Yes, I am using this syntax in my window git config.

**Comment by chrisant996** [comment]
Interesting...

What is the output from running `git status --porcelain -unormal --ignored`?
Dirx runs that git command, and all of the ignored file processing is done by git itself.

If the git command doesn't list `.wtree` as ignored (the `!` character in the porcelain output), then the issue is occurring within git itself.  Which is possible, since eza does not actually invoke git -- instead it uses the libgit2 library, which doesn't always work quite the same as git itself works.

Also, it's working for me:
![image](https://github.com/user-attachments/assets/368783aa-191e-4528-84da-c95df9679a4e)

However, try this:
1. Add the `--debug` flag to the `dirx` invocation.
2. Look for the line starting with "debug: git status in" in the output.
3. Check whether the line includes "plus ignored files".

**Comment by chrisant996** [comment]
Oh -- is the `.wtree` folder empty?

If so, then that's a git issue, not a dirx issue.
The git status command does not list empty folders as ignored.

And technically, if eza and lsd are listing empty folders as ignored then they're behaving differently from git itself.
I know at least eza uses the libgit2 library instead of using git, and libgit2 is known to not behave the same as git in many cases.

**Comment by chrisant996** [comment]
@saumyajyoti when you have a chance please check my previous two replies, and the questions and troubleshooting suggestions in them.

**Comment by chrisant996** [comment]
@saumyajyoti Oh in the eza screenshot you shared, it shows the "empty folder" icon for the `.wtree` folder.

So yes, the issue is that `git` itself doesn't report the `.wtree` folder as being ignored unless it contains at least 1 file.  `eza` uses the libgit2 library instead of using `git` directly, and it seems that libgit2 handles `.gitignore` slightly differently than `git` itself does.

You can observe the same in `git` itself by running:
```
git status --porcelain -unormal --ignored
```

The git status output will not mention the `.wtree` directory, since it's empty.

So, that part is working as expected, and is an issue/quirk in `git` itself.

**Comment by saumyajyoti** [comment]
Hi @chrisant996 , Sorry for late reply. Yes, you are right. It is due to empty folder. git show as ignored if I add a file under it. The behavior is as expected. No more concern.
